version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:21YAyFkPq986LB7J7MarKLyhdoxkYwtrszYLVR+Ne44=  #This isn't supposed to be here, I just have errors and not enought time to fix it
      - API_URL=http://localhost:8000
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/usr/src/app/backend/database/database.sqlite
    volumes:
      - ./backend:/usr/src/app/backend
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_NODE_ENV=development
      - NEXT_API_URL=http://localhost:8000
    # volumes:
    #   - ./frontend:/usr/src/app/frontend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
